In [1]:
import numpy as np

In [4]:
a = np.array([[6,4,24],[1,-9,8]])
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(2, 3)

In [7]:
a.size

6

In [8]:
a[0]

array([ 6,  4, 24])

In [9]:
a[1]

array([ 1, -9,  8])

In [10]:
a[:,0]

array([6, 1])

In [12]:
a[:,2]

array([24,  8])

In [14]:
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [16]:
a[1][2]

8

In [24]:
a = np.array([[6,4,24],[1,-9,8],[1,2,3]])
print(a)

[[ 6  4 24]
 [ 1 -9  8]
 [ 1  2  3]]


In [28]:
a[0:2, :2]

array([[ 6,  4],
       [ 1, -9]])

In [31]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [32]:
a.sum()

10

In [33]:
a.sum(axis=0)

array([4, 6])

In [34]:
a.sum(axis=1)

array([3, 7])

In [35]:
b = a * 2
print(b)

[[2 4]
 [6 8]]


In [36]:
a = np.array([[4,5],[2,0]])
b = np.array([[4,6],[7,1]])
print(a)
print(b)

[[4 5]
 [2 0]]
[[4 6]
 [7 1]]


In [37]:
print(a + b)

[[ 8 11]
 [ 9  1]]


In [38]:
print(a - b)

[[ 0 -1]
 [-5 -1]]


In [39]:
print(a * b)

[[16 30]
 [14  0]]


In [40]:
np.dot(a,b)

array([[51, 29],
       [ 8, 12]])

In [43]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11],[20,21],[30,31]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]


In [44]:
a.shape

(2, 3)

In [45]:
b.shape

(3, 2)

In [46]:
c = np.dot(a,b)
print(c)

[[140 146]
 [320 335]]


In [47]:
d = np.dot(b,a)
print(d)

[[ 54  75  96]
 [104 145 186]
 [154 215 276]]


In [48]:
a = np.array([[1,2,3],[4,5,6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
a.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a = np.array([[0,1,2],[1,7,8],[2,8,9]])
print(a)

[[0 1 2]
 [1 7 8]
 [2 8 9]]


In [52]:
b = a.T
print(b)

[[0 1 2]
 [1 7 8]
 [2 8 9]]


In [53]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
np.trace(a)

15

In [57]:
b = a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
np.trace(b)

15

In [97]:
x = np.array([[8,3],[4,2]])
print(x)

[[8 3]
 [4 2]]


In [98]:
np.linalg.det(x)

3.999999999999999

In [99]:
y = np.array([[1,2,3],[3,1,2],[0,0,1]])
print(y)

[[1 2 3]
 [3 1 2]
 [0 0 1]]


In [100]:
np.linalg.det(y)

-5.000000000000001

In [112]:
z = np.array([[5,6,9],[0,4,5],[0,0,2]])
print(z)

[[5 6 9]
 [0 4 5]
 [0 0 2]]


In [113]:
np.linalg.det(z)

40.0

In [115]:
a = np.array([[4,3],[3,2]])
print(a)

[[4 3]
 [3 2]]


In [116]:
np.linalg.inv(a)

array([[-2.,  3.],
       [ 3., -4.]])

In [118]:
b = np.array([[1,2,3],[0,1,4],[5,6,0]])
print(b)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [119]:
np.linalg.inv(b)

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [120]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [121]:
(1**2 + 2**2 + 3 **2 + 4 **2 ) ** (1/2)

5.477225575051661

In [122]:
np.linalg.norm(a)

5.477225575051661

In [125]:
np.sqrt(np.trace(a.dot(a.T)))

5.477225575051661

In [126]:
import sympy as sp

In [134]:
a = sp.Matrix([[8,3],[4,2]])
a

Matrix([
[8, 3],
[4, 2]])

In [135]:
a.row(0)

Matrix([[8, 3]])

In [136]:
a.col(0)

Matrix([
[8],
[4]])

In [137]:
a.shape

(2, 2)

In [138]:
a.inv()

Matrix([
[1/2, -3/4],
[ -1,    2]])

In [139]:
a.det()

4

In [140]:
sp.zeros(4,5)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [141]:
sp.eye(5)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [142]:
sp.diag(1,2,3,4)

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0],
[0, 0, 0, 4]])